os: 
- linux

language: r
r:
  - oldrel
  - release
  - devel
  
apt_packages:
  - libxml2-dev 
  - libglpk-dev

r_packages:
  - sybil
  - glpkAPI
  - sybilSBML
  - testthat
  - knitr
  - rmarkdown
  
r_build_args: --no-build-vignettes --no-resave-data
r_check_args: --no-build-vignettes

cache: packages
sudo: required